export function circularQueueC(capacity: number): string {
  return `// Auto-generated by Data Structures Visualizer
// Circular Queue (array-based, wrap-around FIFO) — capacity ${capacity}
#include <stdio.h>
#include <stdlib.h>

#define CAPACITY ${capacity}

int queue[CAPACITY];
int front = -1;
int rear  = -1;

typedef enum {
    Q_EMPTY, Q_PARTIALLY_FILLED, Q_FULL,
    Q_OVERFLOW, Q_UNDERFLOW, Q_ENQUEUE, Q_DEQUEUE
} QueueState;

QueueState state = Q_EMPTY;

int is_empty(void) { return front == -1; }
int is_full(void)  { return front != -1 && (rear + 1) % CAPACITY == front; }
int size(void) {
    if (is_empty()) return 0;
    if (rear >= front) return rear - front + 1;
    return CAPACITY - (front - rear - 1);
}

void enqueue(int value) {
    if (is_full()) { state = Q_OVERFLOW; printf("Overflow\\n"); return; }
    if (is_empty()) {
        front = rear = 0;
    } else {
        rear = (rear + 1) % CAPACITY;
    }
    queue[rear] = value;
    state = is_full() ? Q_FULL : Q_PARTIALLY_FILLED;
    printf("enqueued %d\\n", value);
}

int dequeue(void) {
    if (is_empty()) { state = Q_UNDERFLOW; printf("Underflow\\n"); return -1; }
    int v = queue[front];
    if (front == rear) {
        front = rear = -1;
        state = Q_EMPTY;
    } else {
        front = (front + 1) % CAPACITY;
        state = Q_PARTIALLY_FILLED;
    }
    printf("dequeued %d\\n", v);
    return v;
}

int peek(void) {
    if (is_empty()) { printf("Empty\\n"); return -1; }
    return queue[front];
}

int search(int key) {
    if (is_empty()) return -1;
    int i = front;
    for (;;) {
        if (queue[i] == key) return i;
        if (i == rear) break;
        i = (i + 1) % CAPACITY;
    }
    return -1;
}

void display(void) {
    if (is_empty()) { printf("[ ]\\n"); return; }
    printf("[");
    int i = front;
    for (;;) {
        printf(" %d", queue[i]);
        if (i == rear) break;
        i = (i + 1) % CAPACITY;
    }
    printf(" ]  front=%d rear=%d size=%d\\n", front, rear, size());
}

int main(void) {
    int choice, value;
    for (;;) {
        printf("\\n1.Enqueue 2.Dequeue 3.Peek 4.Search 5.Display 6.Exit > ");
        if (scanf("%d", &choice) != 1) break;
        switch (choice) {
            case 1: printf("value: "); scanf("%d", &value); enqueue(value); break;
            case 2: dequeue(); break;
            case 3: printf("front=%d\\n", peek()); break;
            case 4: printf("key: "); scanf("%d", &value);
                    printf("index=%d\\n", search(value)); break;
            case 5: display(); break;
            case 6: return 0;
        }
    }
    return 0;
}
`;
}
