export function stackC(capacity: number): string {
  return `// Auto-generated by Data Structures Visualizer
// Stack (array-based, LIFO) — capacity ${capacity}
#include <stdio.h>
#include <stdlib.h>

#define CAPACITY ${capacity}

int stack[CAPACITY];
int top = -1;

typedef enum {
    S_EMPTY, S_PARTIALLY_FILLED, S_FULL,
    S_OVERFLOW, S_UNDERFLOW, S_PUSH, S_POP
} StackState;

StackState state = S_EMPTY;

int is_empty(void) { return top == -1; }
int is_full(void)  { return top == CAPACITY - 1; }
int size(void)     { return top + 1; }

void push(int value) {
    if (is_full()) { state = S_OVERFLOW; printf("Overflow\\n"); return; }
    stack[++top] = value;
    state = is_full() ? S_FULL : S_PARTIALLY_FILLED;
    printf("pushed %d\\n", value);
}

int pop(void) {
    if (is_empty()) { state = S_UNDERFLOW; printf("Underflow\\n"); return -1; }
    int v = stack[top--];
    state = is_empty() ? S_EMPTY : S_PARTIALLY_FILLED;
    printf("popped %d\\n", v);
    return v;
}

int peek(void) {
    if (is_empty()) { printf("Empty\\n"); return -1; }
    return stack[top];
}

int search(int key) {
    for (int i = top; i >= 0; i--)
        if (stack[i] == key) return i;
    return -1;
}

void display(void) {
    if (is_empty()) { printf("[ ]\\n"); return; }
    printf("[");
    for (int i = 0; i <= top; i++) printf(" %d", stack[i]);
    printf(" ]  top=%d size=%d\\n", top, size());
}

int main(void) {
    int choice, value;
    for (;;) {
        printf("\\n1.Push 2.Pop 3.Peek 4.Search 5.Display 6.Exit > ");
        if (scanf("%d", &choice) != 1) break;
        switch (choice) {
            case 1: printf("value: "); scanf("%d", &value); push(value); break;
            case 2: pop(); break;
            case 3: printf("top=%d\\n", peek()); break;
            case 4: printf("key: "); scanf("%d", &value);
                    printf("index=%d\\n", search(value)); break;
            case 5: display(); break;
            case 6: return 0;
        }
    }
    return 0;
}
`;
}
